/*Relatório de Quantidade de vendas por sabro no ano de 2016 */

SELECT VENDA_SABOR.SABOR,VENDA_SABOR.ANO, VENDA_SABOR.QUANTIDADE,
ROUND((VENDA_SABOR.QUANTIDADE/TOTAL_ANO.QUANTIDADE) * 100,2) AS PARTICIPACAO FROM
(SELECT TP.SABOR,YEAR (NF.DATA_VENDA) AS ANO , SUM(INF.QUANTIDADE) AS QUANTIDADE FROM tabela_de_produtos TP
INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN notas_fiscais NF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC) AS VENDA_SABOR
INNER JOIN
(SELECT YEAR (NF.DATA_VENDA) AS ANO , SUM(INF.QUANTIDADE) AS QUANTIDADE FROM tabela_de_produtos TP
INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN notas_fiscais NF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY  YEAR(NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC) AS TOTAL_ANO
ON VENDA_SABOR.ANO = TOTAL_ANO.ANO;


