/* Ranking de vendas por tamanho no ano de 2016 */

SELECT VENDA_TAMANHO.TAMANHO,VENDA_TAMANHO.ANO, VENDA_TAMANHO.QUANTIDADE,VENDA_TAMANHO.TAMANHO,
ROUND((VENDA_TAMANHO.QUANTIDADE/TOTAL_ANO.QUANTIDADE) * 100,2) AS PARTICIPACAO FROM
(SELECT TP.SABOR,TP.TAMANHO,YEAR (NF.DATA_VENDA) AS ANO , SUM(INF.QUANTIDADE) AS QUANTIDADE FROM tabela_de_produtos TP
INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN notas_fiscais NF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC) AS VENDA_TAMANHO
INNER JOIN
(SELECT YEAR (NF.DATA_VENDA) AS ANO , SUM(INF.QUANTIDADE) AS QUANTIDADE FROM tabela_de_produtos TP
INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN notas_fiscais NF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY  YEAR(NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC) AS TOTAL_ANO
ON VENDA_TAMANHO.ANO = TOTAL_ANO.ANO
ORDER BY VENDA_TAMANHO.TAMANHO DESC